# Generated by Django 5.2.15 on 2026-06-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(help_text='Tema de la clase generado o editado', max_length=200)),
                ('ai_generated_content', models.TextField(blank=True, help_text='El desglose de puntos clave de la IA', null=True)),
                ('pedagogical_methodology', models.CharField(default='Constructivism', max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('country', models.CharField(default='Colombia', max_length=50)),
                ('target_age', models.PositiveIntegerField(help_text='Edad promedio de los niños para ajustar la IA')),
                ('school_grade', models.CharField(help_text='Ej: 3rd Grade, Primaria, etc.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
