# Generated by Django 5.2.15 on 2026-06-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackableResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('IMAGE', 'Image / Infographic'), ('VIDEO', 'Video Link or File'), ('AUDIO', 'Audio / Podcast Lesson'), ('DOC', 'Exam / Worksheet Document')], max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='veda_resources/')),
                ('external_url', models.URLField(blank=True, help_text='Enlace a video de YouTube, audio externo, etc.', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
