# Generated by Django 5.2.15 on 2026-06-20 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources_app', '0001_initial'),
        ('schedule_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackableresource',
            name='class_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='schedule_app.classblock'),
        ),
    ]
