# Generated by Django 4.2.30 on 2026-07-06 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0002_initial'),
        ('resources_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackableresource',
            name='class_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackable_resources', to='schedule_app.classblock'),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('document', 'PDF / Documento'), ('video', 'YouTube / Video'), ('link', 'Enlace Web')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='class_resources/')),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='schedule_app.classblock')),
            ],
        ),
    ]
